### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rkern** [zengrz/CudaMONSEL#1]
Hi! Is there a license for the code in this repository? Thank you!

**Comment by zengrz** [comment]
Hi, thanks for reaching out and sorry about the delay. I really want to say you can use it however you want but I am also curious about what you would be using this for. May I know how you will be using this software?

**Comment by rkern** [comment]
I'm experimenting with SEM denoising algorithms. Thanks!

**Comment by zengrz** [comment]
Cool! Go ahead with your experiments. I am also interested in the research area, feel free to keep me updated if you find anything interesting.

I only have one request: if your experiments lead to any publication, please cite the software. Please find the example citation in README.md. Thanks!

**Comment by rkern** [comment]
Would it be possible for you to select an open source license, like the MIT license of Amphibian? Thanks!

**Comment by zengrz** [comment]
Hi there, I discussed with John and we thought it would good to make this software available to any one who is interested. Even though I do not know fully the implication of this action, I have selected the MIT license like you have suggested. Hope this helps. :)

**Comment by rkern** [comment]
Thank you very much! I deeply appreciate your work on this and your thoughtfulness in releasing it under an open source license. As a longtime participant in the open source scientific Python community, I do lean towards the MIT-like licenses, myself.
